import Head from "next/head";
import Image from "next/image";
import LandingPage from "../Components/Landing/LandingPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weatherly | Getting Weather info with 1 click</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
      </main>
    </div>
  );
}
